const gamesList = [
    { name: "11 11", url: "/11-11.html" },
    { name: "12 Mini Battles 2", url: "/12-mini-battles-2.html" },
    { name: "18 Wheeler Cargo Simulator", url: "/18-wheeler-cargo-simulator.html" },
    { name: "2 Minute Football", url: "/2-minute-football.html" },
    { name: "2048", url: "/2048.html" },
    { name: "3D Monster Truck Skyroads", url: "/3d-monster-truck-skyroads.html" },
    { name: "3D Moto Simulator 2", url: "/3d-moto-simulator-2.html" },
    { name: "4Th And Goal 2022", url: "/4th-and-goal-2022.html" },
    { name: "4X4 Drive Offroad", url: "/4x4-drive-offroad.html" },
    { name: "8 Ball Pool", url: "/8-ball-pool.html" },
    { name: "8Bit Fiesta", url: "/8bit-fiesta.html" },
    { name: "9 Ball Pool", url: "/9-ball-pool.html" },
    { name: "A Dance Of Fire And Ice", url: "/a-dance-of-fire-and-ice.html" },
    { name: "A Pretty Odd Bunny", url: "/a-pretty-odd-bunny.html" },
    { name: "A Pretty Odd Bunny Roast It", url: "/a-pretty-odd-bunny-roast-it.html" },
    { name: "A Small World Cup", url: "/a-small-world-cup.html" },
    { name: "About Us", url: "/about-us.html" },
    { name: "Adventure Drivers", url: "/adventure-drivers.html" },
    { name: "Air Hockey Championship Deluxe", url: "/air-hockey-championship-deluxe.html" },
    { name: "Aliens Nest", url: "/aliens-nest.html" },
    { name: "Amazing Bubble Breaker", url: "/amazing-bubble-breaker.html" },
    { name: "Amazing Bubble Connect", url: "/amazing-bubble-connect.html" },
    { name: "Among Us", url: "/among-us.html" },
    { name: "Animal Arena", url: "/animal-arena.html" },
    { name: "Aqua Thrills", url: "/aqua-thrills.html" },
    { name: "Arcade", url: "/arcade.html" },
    { name: "Archer Master 3D Castle Defense", url: "/archer-master-3d-castle-defense.html" },
    { name: "Archery World Tour", url: "/archery-world-tour.html" },
    { name: "Arithmetica", url: "/arithmetica.html" },
    { name: "Athletics Hero", url: "/athletics-hero.html" },
    { name: "Australian Patience", url: "/australian-patience.html" },
    { name: "Avalanche", url: "/avalanche.html" },
    { name: "Bacon May Die", url: "/bacon-may-die.html" },
    { name: "Bad Ice Cream 2", url: "/bad-ice-cream-2.html" },
    { name: "Bad Ice Cream 3", url: "/bad-ice-cream-3.html" },
    { name: "Barbershop Inc", url: "/barbershop-inc.html" },
    { name: "Basket And Ball", url: "/basket-and-ball.html" },
    { name: "Basket Bros", url: "/basket-bros.html" },
    { name: "Basket Champs", url: "/basket-champs.html" },
    { name: "Basket Random", url: "/basket-random.html" },
    { name: "Basketball Frvr", url: "/basketball-frvr.html" },
    { name: "Basketball Legends", url: "/basketball-legends.html" },
    { name: "Basketball Stars", url: "/basketball-stars.html" },
    { name: "Battle Golf", url: "/battle-golf.html" },
    { name: "Bearsus", url: "/bearsus.html" },
    { name: "Become A Dentist", url: "/become-a-dentist.html" },
    { name: "Become A Fashion Designer", url: "/become-a-fashion-designer.html" },
    { name: "Become A Puppy Groomer", url: "/become-a-puppy-groomer.html" },
    { name: "Big Shot Boxing", url: "/big-shot-boxing.html" },
    { name: "Bike Trials Offroad 1", url: "/bike-trials-offroad-1.html" },
    { name: "Bike Trials Winter 1", url: "/bike-trials-winter-1.html" },
    { name: "Bike Trials Winter 2", url: "/bike-trials-winter-2.html" },
    { name: "Bird Jumper", url: "/bird-jumper.html" },
    { name: "Bitlife", url: "/bitlife.html" },
    { name: "Blob Drop", url: "/blob-drop.html" },
    { name: "Blobby Clicker", url: "/blobby-clicker.html" },
    { name: "Block The Pig", url: "/block-the-pig.html" },
    { name: "Blockins", url: "/blockins.html" },
    { name: "Blocky Cars", url: "/blocky-cars.html" },
    { name: "Blocky Trials", url: "/blocky-trials.html" },
    { name: "Blood Drift", url: "/blood-drift.html" },
    { name: "Blue", url: "/blue.html" },
    { name: "Blumgi Ball", url: "/blumgi-ball.html" },
    { name: "Blumgi Bloom", url: "/blumgi-bloom.html" },
    { name: "Blumgi Dragon", url: "/blumgi-dragon.html" },
    { name: "Blumgi Rocket", url: "/blumgi-rocket.html" },
    { name: "Blumgi Slime", url: "/blumgi-slime.html" },
    { name: "Bomber Royale", url: "/bomber-royale.html" },
    { name: "Bottle Flip", url: "/bottle-flip.html" },
    { name: "Bouncy Basketball", url: "/bouncy-basketball.html" },
    { name: "Bowling Stars", url: "/bowling-stars.html" },
    { name: "Boxing Fighter Shadow Battle", url: "/boxing-fighter-shadow-battle.html" },
    { name: "Boxing Physics 2", url: "/boxing-physics-2.html" },
    { name: "Boxing Random", url: "/boxing-random.html" },
    { name: "Boxrob", url: "/boxrob.html" },
    { name: "Boxrob 2", url: "/boxrob-2.html" },
    { name: "Boxrob 3", url: "/boxrob-3.html" },
    { name: "Brain Dozer", url: "/brain-dozer.html" },
    { name: "Brain Test 4 Tricky Friends", url: "/brain-test-4-tricky-friends.html" },
    { name: "Brain Test Tricky Puzzles", url: "/brain-test-tricky-puzzles.html" },
    { name: "Breaking The Bank", url: "/breaking-the-bank.html" },
    { name: "Bubble Shooter", url: "/bubble-shooter.html" },
    { name: "Bubbles Cool", url: "/bubbles-cool.html" },
    { name: "Bullet Bros", url: "/bullet-bros.html" },
    { name: "Bullet Force", url: "/bullet-force.html" },
    { name: "Bumper Cars Soccer", url: "/bumper-cars-soccer.html" },
    { name: "Bumpy Jumpy", url: "/bumpy-jumpy.html" },
    { name: "Bunny Hop", url: "/bunny-hop.html" },
    { name: "Burnin Rubber 5 Xs", url: "/burnin-rubber-5-xs.html" },
    { name: "Burnin Rubber Crash N Burn", url: "/burnin-rubber-crash-n-burn.html" },
    { name: "Burnout Drift Seaport Max", url: "/burnout-drift-seaport-max.html" },
    { name: "Burnout Extreme Drift 2", url: "/burnout-extreme-drift-2.html" },
    { name: "Burrito Bison", url: "/burrito-bison.html" },
    { name: "Candy Jump", url: "/candy-jump.html" },
    { name: "Car Climb Racing", url: "/car-climb-racing.html" },
    { name: "Car Drift Racers 2", url: "/car-drift-racers-2.html" },
    { name: "Car Eats Car Winter Adventure", url: "/car-eats-car-winter-adventure.html" },
    { name: "Car Rush", url: "/car-rush.html" },
    { name: "Car Simulator Arena", url: "/car-simulator-arena.html" },
    { name: "Cars Thief", url: "/cars-thief.html" },
    { name: "Cars Thief Tank Edition", url: "/cars-thief-tank-edition.html" },
    { name: "Castle Of Chaos", url: "/castle-of-chaos.html" },
    { name: "Cat Coffee Shop", url: "/cat-coffee-shop.html" },
    { name: "Cat Gunner Super Zombie Shoot", url: "/cat-gunner-super-zombie-shoot.html" },
    { name: "Cat Room Blast", url: "/cat-room-blast.html" },
    { name: "Catch The Candy Html5", url: "/catch-the-candy-html5.html" },
    { name: "Catpad", url: "/catpad.html" },
    { name: "Cats", url: "/cats.html" },
    { name: "Cats Love Cake", url: "/cats-love-cake.html" },
    { name: "Cats Love Cake 2", url: "/cats-love-cake-2.html" },
    { name: "Cave Blast", url: "/cave-blast.html" },
    { name: "Chess Grandmaster", url: "/chess-grandmaster.html" },
    { name: "Chessformer", url: "/chessformer.html" },
    { name: "Chicken Merge", url: "/chicken-merge.html" },
    { name: "Chicken Sword Ninja Master", url: "/chicken-sword-ninja-master.html" },
    { name: "Chicky Farm", url: "/chicky-farm.html" },
    { name: "Circloo 2", url: "/circloo-2.html" },
    { name: "City Bike Stunt 2", url: "/city-bike-stunt-2.html" },
    { name: "City Car Driving Stunt Master", url: "/city-car-driving-stunt-master.html" },
    { name: "City Rider", url: "/city-rider.html" },
    { name: "Clash Of Tanks", url: "/clash-of-tanks.html" },
    { name: "Classic Mahjong", url: "/classic-mahjong.html" },
    { name: "Cluster Rush", url: "/cluster-rush.html" },
    { name: "Cluster Rush1", url: "/cluster-rush1.html" },
    { name: "Cluster Rushh", url: "/cluster-rushh.html" },
    { name: "Color Switch", url: "/color-switch.html" },
    { name: "Color Tunnel", url: "/color-tunnel.html" },
    { name: "Color Tunnel 2", url: "/color-tunnel-2.html" },
    { name: "Colorup", url: "/colorup.html" },
    { name: "Combo Crusader", url: "/combo-crusader.html" },
    { name: "Connect 248", url: "/connect-248.html" },
    { name: "Cookie Clicker", url: "/cookie-clicker.html" },
    { name: "Cooking Fast", url: "/cooking-fast.html" },
    { name: "Cooking Fast Halloween", url: "/cooking-fast-halloween.html" },
    { name: "Cosmos Lines", url: "/cosmos-lines.html" },
    { name: "Court Kings 3D", url: "/court-kings-3d.html" },
    { name: "Cover Orange Gangsters", url: "/cover-orange-gangsters.html" },
    { name: "Cover Orange Journey", url: "/cover-orange-journey.html" },
    { name: "Cover Orange Wild West", url: "/cover-orange-wild-west.html" },
    { name: "Cozy Room Design", url: "/cozy-room-design.html" },
    { name: "Craftomation 1", url: "/craftomation-1.html" },
    { name: "Crazy Bikes", url: "/crazy-bikes.html" },
    { name: "Crazy Cars", url: "/crazy-cars.html" },
    { name: "Crossy Road", url: "/crossy-road.html" },
    { name: "Crossy Roadd", url: "/crossy-roadd.html" },
    { name: "Crown Guard", url: "/crown-guard.html" },
    { name: "Cubes King", url: "/cubes-king.html" },
    { name: "Cubies", url: "/cubies.html" },
    { name: "Cubinko", url: "/cubinko.html" },
    { name: "Cute Puzzle Witch", url: "/cute-puzzle-witch.html" },
    { name: "Cyber Cars Punk Racing", url: "/cyber-cars-punk-racing.html" },
    { name: "Daddy Long Legs", url: "/daddy-long-legs.html" },
    { name: "Dadish", url: "/dadish.html" },
    { name: "Dadish 3D", url: "/dadish-3d.html" },
    { name: "Dana Relics For Sale", url: "/dana-relics-for-sale.html" },
    { name: "Dark Runner", url: "/dark-runner.html" },
    { name: "Darts Pro", url: "/darts-pro.html" },
    { name: "Dead Paradise Race Shooter", url: "/dead-paradise-race-shooter.html" },
    { name: "Death Chase", url: "/death-chase.html" },
    { name: "Demolition Derby Crash Racing", url: "/demolition-derby-crash-racing.html" },
    { name: "Descent", url: "/descent.html" },
    { name: "Detective Dan", url: "/detective-dan.html" },
    { name: "Detective Loupe Puzzle", url: "/detective-loupe-puzzle.html" },
    { name: "Digging Master", url: "/digging-master.html" },
    { name: "Dino Bros", url: "/dino-bros.html" },
    { name: "Dinosaur Game", url: "/dinosaur-game.html" },
    { name: "Dmca", url: "/dmca.html" },
    { name: "Doctor Acorn 3", url: "/doctor-acorn-3.html" },
    { name: "Doctor Hero", url: "/doctor-hero.html" },
    { name: "Doctor Teeth", url: "/doctor-teeth.html" },
    { name: "Doctor Teeth 2", url: "/doctor-teeth-2.html" },
    { name: "Doodle Champion Island", url: "/doodle-champion-island.html" },
    { name: "Doodle Jump", url: "/doodle-jump.html" },
    { name: "Double Panda", url: "/double-panda.html" },
    { name: "Dragon Simulator 3D", url: "/dragon-simulator-3d.html" },
    { name: "Draw Pixel Art", url: "/draw-pixel-art.html" },
    { name: "Draw The Hill", url: "/draw-the-hill.html" },
    { name: "Dreadhead Parkour", url: "/dreadhead-parkour.html" },
    { name: "Dress Up", url: "/dress-up.html" },
    { name: "Dress Up The Lovely Princess", url: "/dress-up-the-lovely-princess.html" },
    { name: "Drift Boss", url: "/drift-boss.html" },
    { name: "Drift Hunters", url: "/drift-hunters.html" },
    { name: "Driftwave", url: "/driftwave.html" },
    { name: "Drive Mad", url: "/drive-mad.html" },
    { name: "Drunken Duel", url: "/drunken-duel.html" },
    { name: "Dubai Police Parking 2", url: "/dubai-police-parking-2.html" },
    { name: "Duck Life", url: "/duck-life.html" },
    { name: "Duck Life 2 World Champion", url: "/duck-life-2-world-champion.html" },
    { name: "Duck Life 3 Evolution", url: "/duck-life-3-evolution.html" },
    { name: "Duck Life 4", url: "/duck-life-4.html" },
    { name: "Duck Life Battle", url: "/duck-life-battle.html" },
    { name: "Duck Pond Mahjong", url: "/duck-pond-mahjong.html" },
    { name: "Dungeons Dressups", url: "/dungeons-dressups.html" },
    { name: "Dunk Perfect", url: "/dunk-perfect.html" },
    { name: "Dunkbrush", url: "/dunkbrush.html" },
    { name: "Duo Survival", url: "/duo-survival.html" },
    { name: "Duo Survival 2", url: "/duo-survival-2.html" },
    { name: "Duo Survival 3", url: "/duo-survival-3.html" },
    { name: "Duo Vikings", url: "/duo-vikings.html" },
    { name: "Duo Vikings 2", url: "/duo-vikings-2.html" },
    { name: "Duo Vikings 3", url: "/duo-vikings-3.html" },
    { name: "Dyna Boy", url: "/dyna-boy.html" },
    { name: "Earn To Die", url: "/earn-to-die.html" },
    { name: "Eggbot Vs Zombies", url: "/eggbot-vs-zombies.html" },
    { name: "Eggy Car", url: "/eggy-car.html" },
    { name: "Element Blocks", url: "/element-blocks.html" },
    { name: "Energy", url: "/energy.html" },
    { name: "Error", url: "/error.html" },
    { name: "Escape Road", url: "/escape-road.html" },
    { name: "Escaping The Prison", url: "/escaping-the-prison.html" },
    { name: "Evo City Driving", url: "/evo-city-driving.html" },
    { name: "Extreme Car Driving Simulator", url: "/extreme-car-driving-simulator.html" },
    { name: "Extreme Motorcycle Simulator", url: "/extreme-motorcycle-simulator.html" },
    { name: "Extreme Off Road Cars", url: "/extreme-off-road-cars.html" },
    { name: "Extreme Off Road Cars 3 Cargo", url: "/extreme-off-road-cars-3-cargo.html" },
    { name: "Factory Balls Forever", url: "/factory-balls-forever.html" },
    { name: "Fancy Pants", url: "/fancy-pants.html" },
    { name: "Fancy Pants 2", url: "/fancy-pants-2.html" },
    { name: "Fancy Pants 3", url: "/fancy-pants-3.html" },
    { name: "Farm Battles", url: "/farm-battles.html" },
    { name: "Fast Food Dumpster Adventure", url: "/fast-food-dumpster-adventure.html" },
    { name: "Final Ninja Html5", url: "/final-ninja-html5.html" },
    { name: "Finger Cook", url: "/finger-cook.html" },
    { name: "Fireboy And Watergirl 1 Forest Temple", url: "/fireboy-and-watergirl-1-forest-temple.html" },
    { name: "Fireboy And Watergirl 2 Light Temple", url: "/fireboy-and-watergirl-2-light-temple.html" },
    { name: "Fireboy And Watergirl 4 Crystal Temple", url: "/fireboy-and-watergirl-4-crystal-temple.html" },
    { name: "Fireboy And Watergirl 5 Elements", url: "/fireboy-and-watergirl-5-elements.html" },
    { name: "Fireboy Watergirl 3 Ice Temple", url: "/fireboy-watergirl-3-ice-temple.html" },
    { name: "Fireboy Watergirl 6 Fairy Tales", url: "/fireboy-watergirl-6-fairy-tales.html" },
    { name: "Flags Maniac", url: "/flags-maniac.html" },
    { name: "Flags Quiz", url: "/flags-quiz.html" },
    { name: "Flappy Bird Origin", url: "/flappy-bird-origin.html" },
    { name: "Fleeing The Complex", url: "/fleeing-the-complex.html" },
    { name: "Flip Bros", url: "/flip-bros.html" },
    { name: "Flip Runner", url: "/flip-runner.html" },
    { name: "Flying Car Simulator", url: "/flying-car-simulator.html" },
    { name: "Fnf B Sides", url: "/fnf-b-sides.html" },
    { name: "Fnf Hatsune Miku", url: "/fnf-hatsune-miku.html" },
    { name: "Fnf Shaggy Matt", url: "/fnf-shaggy-matt.html" },
    { name: "Fnf Xe", url: "/fnf-xe.html" },
    { name: "Football Blitz", url: "/football-blitz.html" },
    { name: "Football Penalty Champions", url: "/football-penalty-champions.html" },
    { name: "Footyzag", url: "/footyzag.html" },
    { name: "Forgotten Hill Memento Love Beyond", url: "/forgotten-hill-memento-love-beyond.html" },
    { name: "Forgotten Hill The Wardrobe", url: "/forgotten-hill-the-wardrobe.html" },
    { name: "Forgotten Hill The Wardrobe 3", url: "/forgotten-hill-the-wardrobe-3.html" },
    { name: "Forgotten Hill The Wardrobe 4", url: "/forgotten-hill-the-wardrobe-4.html" },
    { name: "Fortride Open World", url: "/fortride-open-world.html" },
    { name: "Four In A Row", url: "/four-in-a-row.html" },
    { name: "Fox Simulator 3D", url: "/fox-simulator-3d.html" },
    { name: "Free Kick Screamers", url: "/free-kick-screamers.html" },
    { name: "Free The Key", url: "/free-the-key.html" },
    { name: "Freefall Apart", url: "/freefall-apart.html" },
    { name: "Freeway Fury", url: "/freeway-fury.html" },
    { name: "Fruit Ninja", url: "/fruit-ninja.html" },
    { name: "Funny Dentist Surgery", url: "/funny-dentist-surgery.html" },
    { name: "Funny Ear Surgery", url: "/funny-ear-surgery.html" },
    { name: "Funny Eye Surgery", url: "/funny-eye-surgery.html" },
    { name: "Funny Throat Surgery", url: "/funny-throat-surgery.html" },
    { name: "Furious Racing 3D", url: "/furious-racing-3d.html" },
    { name: "Fury Wars", url: "/fury-wars.html" },
    { name: "G Switch 3", url: "/g-switch-3.html" },
    { name: "G Switch 4", url: "/g-switch-4.html" },
    { name: "Game Of Farmers", url: "/game-of-farmers.html" },
    { name: "Gangster Contract Mafia Wars", url: "/gangster-contract-mafia-wars.html" },
    { name: "Gem 11", url: "/gem-11.html" },
    { name: "Genie Quest", url: "/genie-quest.html" },
    { name: "Geometry Dash", url: "/geometry-dash.html" },
    { name: "Geometry Dash Lite", url: "/geometry-dash-lite.html" },
    { name: "Getaway Shootout", url: "/getaway-shootout.html" },
    { name: "Gladiator True Story", url: "/gladiator-true-story.html" },
    { name: "Glam Girl Dress Up And Makeover", url: "/glam-girl-dress-up-and-makeover.html" },
    { name: "Go Kart Go Ultra", url: "/go-kart-go-ultra.html" },
    { name: "Goat Vs Zombies", url: "/goat-vs-zombies.html" },
    { name: "Gobble", url: "/gobble.html" },
    { name: "Gobdun", url: "/gobdun.html" },
    { name: "Gold Digger Frvr", url: "/gold-digger-frvr.html" },
    { name: "Golf Champions", url: "/golf-champions.html" },
    { name: "Golfinity", url: "/golfinity.html" },
    { name: "Goose Game", url: "/goose-game.html" },
    { name: "Grand Prix Hero", url: "/grand-prix-hero.html" },
    { name: "Grindcraft", url: "/grindcraft.html" },
    { name: "Grow Up The Cats", url: "/grow-up-the-cats.html" },
    { name: "Growmi", url: "/growmi.html" },
    { name: "Gun Mayhem", url: "/gun-mayhem.html" },
    { name: "Gun Mayhem 3", url: "/gun-mayhem-3.html" },
    { name: "Gunspin", url: "/gunspin.html" },
    { name: "Hammer 2 Reloaded", url: "/hammer-2-reloaded.html" },
    { name: "Hangman", url: "/hangman.html" },
    { name: "Head Soccer 2023", url: "/head-soccer-2023.html" },
    { name: "Hextris", url: "/hextris.html" },
    { name: "Hide And Smash", url: "/hide-and-smash.html" },
    { name: "Highway Bike Simulator", url: "/highway-bike-simulator.html" },
    { name: "Highway Racer 3D", url: "/highway-racer-3d.html" },
    { name: "Highway Rider Extreme", url: "/highway-rider-extreme.html" },
    { name: "Highway Traffic", url: "/highway-traffic.html" },
    { name: "Hills Of Steel", url: "/hills-of-steel.html" },
    { name: "Hipster Vs Rockers", url: "/hipster-vs-rockers.html" },
    { name: "Home", url: "/home.html" },
    { name: "Hop Chop", url: "/hop-chop.html" },
    { name: "Hop Warp", url: "/hop-warp.html" },
    { name: "Hoppenhelm", url: "/hoppenhelm.html" },
    { name: "House Of Hazards", url: "/house-of-hazards.html" },
    { name: "Hover Racer", url: "/hover-racer.html" },
    { name: "Hypersnake", url: "/hypersnake.html" },
    { name: "Ice Cream Please", url: "/ice-cream-please.html" },
    { name: "Icy Purple Head 3", url: "/icy-purple-head-3.html" },
    { name: "Idle Ants", url: "/idle-ants.html" },
    { name: "Idle Cowshed", url: "/idle-cowshed.html" },
    { name: "Idle Digging Tycoon", url: "/idle-digging-tycoon.html" },
    { name: "Idle Gold Miner", url: "/idle-gold-miner.html" },
    { name: "Idle Lumber Inc", url: "/idle-lumber-inc.html" },
    { name: "Idle Zoo Safari Rescue", url: "/idle-zoo-safari-rescue.html" },
    { name: "Impossible 13", url: "/impossible-13.html" },
    { name: "Impossible Monster Truck Race", url: "/impossible-monster-truck-race.html" },
    { name: "Impossible Tic Tac Toe", url: "/impossible-tic-tac-toe.html" },
    { name: "Infinite Soccer", url: "/infinite-soccer.html" },
    { name: "Infinity Loop", url: "/infinity-loop.html" },
    { name: "Into The Pit", url: "/into-the-pit.html" },
    { name: "Izowave Build And Defend", url: "/izowave-build-and-defend.html" },
    { name: "James Gun", url: "/james-gun.html" },
    { name: "Jamming Car Escape", url: "/jamming-car-escape.html" },
    { name: "Jelly Truck", url: "/jelly-truck.html" },
    { name: "Jetpack Joyride", url: "/jetpack-joyride.html" },
    { name: "Jigsaw Photo Puzzle Christmas", url: "/jigsaw-photo-puzzle-christmas.html" },
    { name: "Jigsaw Photo Puzzle Winter", url: "/jigsaw-photo-puzzle-winter.html" },
    { name: "Joko Permana", url: "/joko-permana.html" },
    { name: "Jollyworld", url: "/jollyworld.html" },
    { name: "Jr Chess", url: "/jr-chess.html" },
    { name: "Jump And Hover", url: "/jump-and-hover.html" },
    { name: "Jumping Shell", url: "/jumping-shell.html" },
    { name: "Jungle Bubble Shooter Mania", url: "/jungle-bubble-shooter-mania.html" },
    { name: "Just Park It 11", url: "/just-park-it-11.html" },
    { name: "Just Park It 12", url: "/just-park-it-12.html" },
    { name: "Kart Race 3D", url: "/kart-race-3d.html" },
    { name: "Kart Wars", url: "/kart-wars.html" },
    { name: "Kix Dream Soccer", url: "/kix-dream-soccer.html" },
    { name: "Kubi Pets", url: "/kubi-pets.html" },
    { name: "La Petite Avril", url: "/la-petite-avril.html" },
    { name: "Lands Of Blight", url: "/lands-of-blight.html" },
    { name: "Last Warriors", url: "/last-warriors.html" },
    { name: "Lava Bird", url: "/lava-bird.html" },
    { name: "Leader Strike", url: "/leader-strike.html" },
    { name: "Ledge Throw", url: "/ledge-throw.html" },
    { name: "Lethal Sniper 3D Army Soldier", url: "/lethal-sniper-3d-army-soldier.html" },
    { name: "Level Devil", url: "/level-devil.html" },
    { name: "Life Choices Life Simulator", url: "/life-choices-life-simulator.html" },
    { name: "Life The Game", url: "/life-the-game.html" },
    { name: "Light The Lamp", url: "/light-the-lamp.html" },
    { name: "Linebacker Alley 2", url: "/linebacker-alley-2.html" },
    { name: "Lines To Fill", url: "/lines-to-fill.html" },
    { name: "Little Master Cricket", url: "/little-master-cricket.html" },
    { name: "Logic Master 1", url: "/logic-master-1.html" },
    { name: "Lords Of Gomoku", url: "/lords-of-gomoku.html" },
    { name: "Lovely Fox", url: "/lovely-fox.html" },
    { name: "Ludo Hero", url: "/ludo-hero.html" },
    { name: "Lurkers Io", url: "/lurkers-io.html" },
    { name: "Mad Day", url: "/mad-day.html" },
    { name: "Mad Truck Challenge Special", url: "/mad-truck-challenge-special.html" },
    { name: "Madalin Stunt Cars 2", url: "/madalin-stunt-cars-2.html" },
    { name: "Madalin Stunt Cars 3", url: "/madalin-stunt-cars-3.html" },
    { name: "Madzoong", url: "/madzoong.html" },
    { name: "Mafia Wars", url: "/mafia-wars.html" },
    { name: "Magic Bridge", url: "/magic-bridge.html" },
    { name: "Mahjong", url: "/mahjong.html" },
    { name: "Mahjong Linker Kyodai Game", url: "/mahjong-linker-kyodai-game.html" },
    { name: "Make It Meme", url: "/make-it-meme.html" },
    { name: "Marble Dash", url: "/marble-dash.html" },
    { name: "Masked Forces", url: "/masked-forces.html" },
    { name: "Math Mahjong Relax", url: "/math-mahjong-relax.html" },
    { name: "Maze Path Of Light", url: "/maze-path-of-light.html" },
    { name: "Meow Merge", url: "/meow-merge.html" },
    { name: "Merge Cyber Racers", url: "/merge-cyber-racers.html" },
    { name: "Merge Party", url: "/merge-party.html" },
    { name: "Merge Round Racers", url: "/merge-round-racers.html" },
    { name: "Merge To Million", url: "/merge-to-million.html" },
    { name: "Mermaid Dress Up", url: "/mermaid-dress-up.html" },
    { name: "Mimelet", url: "/mimelet.html" },
    { name: "Minecraft Builder", url: "/minecraft-builder.html" },
    { name: "Minesweeper", url: "/minesweeper.html" },
    { name: "Mini Guardians Castle Defense", url: "/mini-guardians-castle-defense.html" },
    { name: "Mini Train", url: "/mini-train.html" },
    { name: "Misland", url: "/misland.html" },
    { name: "Monster Merge", url: "/monster-merge.html" },
    { name: "Monster Tracks", url: "/monster-tracks.html" },
    { name: "Monster Truck Racing Arena", url: "/monster-truck-racing-arena.html" },
    { name: "Monsters Wheels Special", url: "/monsters-wheels-special.html" },
    { name: "Mosaic Puzzle Art", url: "/mosaic-puzzle-art.html" },
    { name: "Moto Maniac", url: "/moto-maniac.html" },
    { name: "Moto Maniac 2", url: "/moto-maniac-2.html" },
    { name: "Moto Road Rash 3D", url: "/moto-road-rash-3d.html" },
    { name: "Moto Space Racing 2 Player", url: "/moto-space-racing-2-player.html" },
    { name: "Moto X3M", url: "/moto-x3m.html" },
    { name: "Moto X3M 2", url: "/moto-x3m-2.html" },
    { name: "Moto X3M Pool Party", url: "/moto-x3m-pool-party.html" },
    { name: "Moto X3M Spooky Land", url: "/moto-x3m-spooky-land.html" },
    { name: "Moto X3M Winter", url: "/moto-x3m-winter.html" },
    { name: "Moto X3M Winterr", url: "/moto-x3m-winterr.html" },
    { name: "Moving Truck Bounty", url: "/moving-truck-bounty.html" },
    { name: "Mowing Mazes", url: "/mowing-mazes.html" },
    { name: "Mummys Path Deluxe", url: "/mummys-path-deluxe.html" },
    { name: "Murder", url: "/murder.html" },
    { name: "My Pony My Little Race", url: "/my-pony-my-little-race.html" },
    { name: "Mystical Birdlink", url: "/mystical-birdlink.html" },
    { name: "N Gon", url: "/n-gon.html" },
    { name: "Nightpoint Io", url: "/nightpoint-io.html" },
    { name: "Noob Drive", url: "/noob-drive.html" },
    { name: "Noob Hook", url: "/noob-hook.html" },
    { name: "Nuggetroyale Io", url: "/nuggetroyale-io.html" },
    { name: "Odd Bot Out", url: "/odd-bot-out.html" },
    { name: "Off Road Rain Cargo Simulator", url: "/off-road-rain-cargo-simulator.html" },
    { name: "Offroader V5", url: "/offroader-v5.html" },
    { name: "One Button Bounce", url: "/one-button-bounce.html" },
    { name: "One Hundred Castles Solitaire", url: "/one-hundred-castles-solitaire.html" },
    { name: "Onet Fruit Classic", url: "/onet-fruit-classic.html" },
    { name: "Ooze Odyssey", url: "/ooze-odyssey.html" },
    { name: "Orange", url: "/orange.html" },
    { name: "Ovo", url: "/ovo.html" },
    { name: "Ovo Dimensions", url: "/ovo-dimensions.html" },
    { name: "Pack A Bag", url: "/pack-a-bag.html" },
    { name: "Paint Strike", url: "/paint-strike.html" },
    { name: "Panda Bubble Shooter", url: "/panda-bubble-shooter.html" },
    { name: "Papa Louie When Pizzas Attack", url: "/papa-louie-when-pizzas-attack.html" },
    { name: "Papas Cheeseria", url: "/papas-cheeseria.html" },
    { name: "Papas Donuteria", url: "/papas-donuteria.html" },
    { name: "Papas Hotdoggeria", url: "/papas-hotdoggeria.html" },
    { name: "Papas Pancakeria", url: "/papas-pancakeria.html" },
    { name: "Papas Pizzeria", url: "/papas-pizzeria.html" },
    { name: "Papas Taco Mia", url: "/papas-taco-mia.html" },
    { name: "Paper Io 2", url: "/paper-io-2.html" },
    { name: "Parking Fury", url: "/parking-fury.html" },
    { name: "Parking Fury 2", url: "/parking-fury-2.html" },
    { name: "Parking Fury 3D", url: "/parking-fury-3d.html" },
    { name: "Parking Fury 3D Beach City", url: "/parking-fury-3d-beach-city.html" },
    { name: "Parking Fury 3D Bounty Hunter", url: "/parking-fury-3d-bounty-hunter.html" },
    { name: "Parking Fury 3D Night Thief", url: "/parking-fury-3d-night-thief.html" },
    { name: "Parkmania", url: "/parkmania.html" },
    { name: "Parkour Block 3D", url: "/parkour-block-3d.html" },
    { name: "Penalty Rivals", url: "/penalty-rivals.html" },
    { name: "Penalty Shooters 2", url: "/penalty-shooters-2.html" },
    { name: "Peppa Pig Basketball", url: "/peppa-pig-basketball.html" },
    { name: "Perfect Peel", url: "/perfect-peel.html" },
    { name: "Photo Puzzle Slide Edition", url: "/photo-puzzle-slide-edition.html" },
    { name: "Ping Pong Chaos", url: "/ping-pong-chaos.html" },
    { name: "Pink", url: "/pink.html" },
    { name: "Pirates Merger", url: "/pirates-merger.html" },
    { name: "Pixel Gun Survival", url: "/pixel-gun-survival.html" },
    { name: "Pixel Puzzles", url: "/pixel-puzzles.html" },
    { name: "Pizzafall", url: "/pizzafall.html" },
    { name: "Pizzapunk", url: "/pizzapunk.html" },
    { name: "Plactions", url: "/plactions.html" },
    { name: "Platform Countdown", url: "/platform-countdown.html" },
    { name: "Policy And Privacy", url: "/policy-and-privacy.html" },
    { name: "Pond Race", url: "/pond-race.html" },
    { name: "Pony Dressup 2", url: "/pony-dressup-2.html" },
    { name: "Pony Run Magic Trails", url: "/pony-run-magic-trails.html" },
    { name: "Pool Club", url: "/pool-club.html" },
    { name: "Poor Bunny", url: "/poor-bunny.html" },
    { name: "Popit Vs Spinner", url: "/popit-vs-spinner.html" },
    { name: "Power Badminton", url: "/power-badminton.html" },
    { name: "Princess Room Cleaning", url: "/princess-room-cleaning.html" },
    { name: "Prismo Puzzles", url: "/prismo-puzzles.html" },
    { name: "Puffy Cat", url: "/puffy-cat.html" },
    { name: "Pull My Tongue", url: "/pull-my-tongue.html" },
    { name: "Puzzle", url: "/puzzle.html" },
    { name: "Rabbit Samurai", url: "/rabbit-samurai.html" },
    { name: "Racing", url: "/racing.html" },
    { name: "Raft Wars", url: "/raft-wars.html" },
    { name: "Raft Wars 2", url: "/raft-wars-2.html" },
    { name: "Raft Wars Multiplayer", url: "/raft-wars-multiplayer.html" },
    { name: "Ragdoll Hit", url: "/ragdoll-hit.html" },
    { name: "Rainbow Star Pinball", url: "/rainbow-star-pinball.html" },
    { name: "Rally Champion", url: "/rally-champion.html" },
    { name: "Rally Point", url: "/rally-point.html" },
    { name: "Rally Point 2", url: "/rally-point-2.html" },
    { name: "Rally Point 3", url: "/rally-point-3.html" },
    { name: "Rally Point 5", url: "/rally-point-5.html" },
    { name: "Real Cars In City", url: "/real-cars-in-city.html" },
    { name: "Real Simulator Monster Truck", url: "/real-simulator-monster-truck.html" },
    { name: "Rebels Clash", url: "/rebels-clash.html" },
    { name: "Recoil", url: "/recoil.html" },
    { name: "Red Ball 4", url: "/red-ball-4.html" },
    { name: "Refuge Solitaire", url: "/refuge-solitaire.html" },
    { name: "Retro Bowl", url: "/retro-bowl.html" },
    { name: "Retro Highway", url: "/retro-highway.html" },
    { name: "Rhomb", url: "/rhomb.html" },
    { name: "Rocket Pult", url: "/rocket-pult.html" },
    { name: "Rocket Soccer Derby", url: "/rocket-soccer-derby.html" },
    { name: "Rodeo Stampede Savannah", url: "/rodeo-stampede-savannah.html" },
    { name: "Roly Poly Monsters", url: "/roly-poly-monsters.html" },
    { name: "Rooftop Snipers", url: "/rooftop-snipers.html" },
    { name: "Rooftop Snipers 2", url: "/rooftop-snipers-2.html" },
    { name: "Rugby Rush", url: "/rugby-rush.html" },
    { name: "Run 3 Editor", url: "/run-3-editor.html" },
    { name: "Runman Race Around The World", url: "/runman-race-around-the-world.html" },
    { name: "Running Fred", url: "/running-fred.html" },
    { name: "Rush Race Motocross", url: "/rush-race-motocross.html" },
    { name: "Rusher Crusher", url: "/rusher-crusher.html" },
    { name: "Sausage Flip", url: "/sausage-flip.html" },
    { name: "School Bus Demolition Derby", url: "/school-bus-demolition-derby.html" },
    { name: "Scrap Divers", url: "/scrap-divers.html" },
    { name: "Scrap Metal", url: "/scrap-metal.html" },
    { name: "Shady Bears", url: "/shady-bears.html" },
    { name: "Shape Fold Animals", url: "/shape-fold-animals.html" },
    { name: "Shape Fold Html5", url: "/shape-fold-html5.html" },
    { name: "Shape Fold Nature", url: "/shape-fold-nature.html" },
    { name: "Sharkio", url: "/sharkio.html" },
    { name: "Shoot Stickman", url: "/shoot-stickman.html" },
    { name: "Shooting", url: "/shooting.html" },
    { name: "Shootz", url: "/shootz.html" },
    { name: "Short Life", url: "/short-life.html" },
    { name: "Short Ride", url: "/short-ride.html" },
    { name: "Shortcut Race", url: "/shortcut-race.html" },
    { name: "Simply Prop Hunt", url: "/simply-prop-hunt.html" },
    { name: "Simulation", url: "/simulation.html" },
    { name: "Sketchbook 04", url: "/sketchbook-04.html" },
    { name: "Skibidi Shooter", url: "/skibidi-shooter.html" },
    { name: "Skiing Fred", url: "/skiing-fred.html" },
    { name: "Sky Mad", url: "/sky-mad.html" },
    { name: "Slalom Hero", url: "/slalom-hero.html" },
    { name: "Slime Laboratory", url: "/slime-laboratory.html" },
    { name: "Slime Laboratory 3", url: "/slime-laboratory-3.html" },
    { name: "Slime Road", url: "/slime-road.html" },
    { name: "Sling Drift", url: "/sling-drift.html" },
    { name: "Sling Kong", url: "/sling-kong.html" },
    { name: "Slope", url: "/slope.html" },
    { name: "Slope 2", url: "/slope-2.html" },
    { name: "Slope 2 Multiplayer", url: "/slope-2-multiplayer.html" },
    { name: "Slope 3", url: "/slope-3.html" },
    { name: "Slope Ball", url: "/slope-ball.html" },
    { name: "Slope Run", url: "/slope-run.html" },
    { name: "Slope Tunnel", url: "/slope-tunnel.html" },
    { name: "Slopey", url: "/slopey.html" },
    { name: "Slot Car Racing", url: "/slot-car-racing.html" },
    { name: "Smash Karts", url: "/smash-karts.html" },
    { name: "Snail Bob 6", url: "/snail-bob-6.html" },
    { name: "Snake Cool", url: "/snake-cool.html" },
    { name: "Snake Is Mlg Edition", url: "/snake-is-mlg-edition.html" },
    { name: "Snake Solver", url: "/snake-solver.html" },
    { name: "Snakeio", url: "/snakeio.html" },
    { name: "Snakes And Ladders", url: "/snakes-and-ladders.html" },
    { name: "Sniper Gun Shooting", url: "/sniper-gun-shooting.html" },
    { name: "Snow Rider 3D", url: "/ubg.html" },
    { name: "Soccar", url: "/soccar.html" },
    { name: "Soccer Random", url: "/soccer-random.html" },
    { name: "Soccer Skills Champions League", url: "/soccer-skills-champions-league.html" },
    { name: "Soccer Skills Euro Cup", url: "/soccer-skills-euro-cup.html" },
    { name: "Soccer Skills World Cup", url: "/soccer-skills-world-cup.html" },
    { name: "Solitaire", url: "/solitaire.html" },
    { name: "Solitaire Reverse", url: "/solitaire-reverse.html" },
    { name: "Space Major Miner", url: "/space-major-miner.html" },
    { name: "Space Thing", url: "/space-thing.html" },
    { name: "Speed Boat Extreme Racing", url: "/speed-boat-extreme-racing.html" },
    { name: "Speed Pool King", url: "/speed-pool-king.html" },
    { name: "Sports", url: "/sports.html" },
    { name: "Spot The Differences", url: "/spot-the-differences.html" },
    { name: "Stack", url: "/stack.html" },
    { name: "Stack Ball", url: "/stack-ball.html" },
    { name: "Stack City", url: "/stack-city.html" },
    { name: "Stacktris", url: "/stacktris.html" },
    { name: "Stair Race 3D", url: "/stair-race-3d.html" },
    { name: "Stealing The Diamond", url: "/stealing-the-diamond.html" },
    { name: "Stick Defenders", url: "/stick-defenders.html" },
    { name: "Stick Fortress", url: "/stick-fortress.html" },
    { name: "Stick Merge", url: "/stick-merge.html" },
    { name: "Stickman Archero Fight", url: "/stickman-archero-fight.html" },
    { name: "Stickman Army Team Battle", url: "/stickman-army-team-battle.html" },
    { name: "Stickman Army The Resistance", url: "/stickman-army-the-resistance.html" },
    { name: "Stickman Bike", url: "/stickman-bike.html" },
    { name: "Stickman Bike Pr", url: "/stickman-bike-pr.html" },
    { name: "Stickman Boxing Ko Champion", url: "/stickman-boxing-ko-champion.html" },
    { name: "Stickman Bridge Constructor", url: "/stickman-bridge-constructor.html" },
    { name: "Stickman Climb 2", url: "/stickman-climb-2.html" },
    { name: "Stickman Crazy Box", url: "/stickman-crazy-box.html" },
    { name: "Stickman Fight Ragdoll", url: "/stickman-fight-ragdoll.html" },
    { name: "Stickman Fighter Epic Battle 2", url: "/stickman-fighter-epic-battle-2.html" },
    { name: "Stickman Fighter Mega Brawl", url: "/stickman-fighter-mega-brawl.html" },
    { name: "Stickman Golf", url: "/stickman-golf.html" },
    { name: "Stickman Hook", url: "/stickman-hook.html" },
    { name: "Stickman Parkour 3", url: "/stickman-parkour-3.html" },
    { name: "Stickman School Run", url: "/stickman-school-run.html" },
    { name: "Stock Car Hero", url: "/stock-car-hero.html" },
    { name: "Strategy", url: "/strategy.html" },
    { name: "Street Ball Jam", url: "/street-ball-jam.html" },
    { name: "Stunt Car Challenge 3", url: "/stunt-car-challenge-3.html" },
    { name: "Stupid Zombies", url: "/stupid-zombies.html" },
    { name: "Stupid Zombies 2", url: "/stupid-zombies-2.html" },
    { name: "Subway Runner", url: "/subway-runner.html" },
    { name: "Subway Surfers", url: "/subway-surfers.html" },
    { name: "Subway Surfers Beijing", url: "/subway-surfers-beijing.html" },
    { name: "Subway Surfers Houston", url: "/subway-surfers-houston.html" },
    { name: "Subway Surfers Monaco", url: "/subway-surfers-monaco.html" },
    { name: "Subway Surfers Newyork", url: "/subway-surfers-newyork.html" },
    { name: "Sudoku", url: "/sudoku.html" },
    { name: "Sudoku Calendar", url: "/sudoku-calendar.html" },
    { name: "Sudoku Village", url: "/sudoku-village.html" },
    { name: "Sumo Party", url: "/sumo-party.html" },
    { name: "Super Bike The Champion", url: "/super-bike-the-champion.html" },
    { name: "Super Fowlst 2", url: "/super-fowlst-2.html" },
    { name: "Super Girl Story", url: "/super-girl-story.html" },
    { name: "Super Hexbee Merger", url: "/super-hexbee-merger.html" },
    { name: "Super Liquid Soccer", url: "/super-liquid-soccer.html" },
    { name: "Super Mario Bros", url: "/super-mario-bros.html" },
    { name: "Super Mx The Champion", url: "/super-mx-the-champion.html" },
    { name: "Super Racing Gt Drag Pro", url: "/super-racing-gt-drag-pro.html" },
    { name: "Super Speeder", url: "/super-speeder.html" },
    { name: "Super Star Car", url: "/super-star-car.html" },
    { name: "Super Tunnel Rush", url: "/super-tunnel-rush.html" },
    { name: "Superbike Hero", url: "/superbike-hero.html" },
    { name: "Superbrawl", url: "/superbrawl.html" },
    { name: "Supernova", url: "/supernova.html" },
    { name: "Survival Express", url: "/survival-express.html" },
    { name: "Sweety Mahjong", url: "/sweety-mahjong.html" },
    { name: "Swingo", url: "/swingo.html" },
    { name: "Tag", url: "/tag.html" },
    { name: "Tag 2", url: "/tag-2.html" },
    { name: "Tank Ball Monster Battle", url: "/tank-ball-monster-battle.html" },
    { name: "Tanuki Sunset", url: "/tanuki-sunset.html" },
    { name: "Teleport Jumper", url: "/teleport-jumper.html" },
    { name: "Temple Of Boom", url: "/temple-of-boom.html" },
    { name: "Temple Run", url: "/temple-run.html" },
    { name: "Temple Run 2", url: "/temple-run-2.html" },
    { name: "Temple Run 2 Frozen Festival", url: "/temple-run-2-frozen-festival.html" },
    { name: "Temple Run 2 Frozen Shadows", url: "/temple-run-2-frozen-shadows.html" },
    { name: "Temple Run 2 Holi Festival", url: "/temple-run-2-holi-festival.html" },
    { name: "Temple Run 2 Jungle Fall", url: "/temple-run-2-jungle-fall.html" },
    { name: "Terms Of Use", url: "/terms-of-use.html" },
    { name: "Tetra Blocks", url: "/tetra-blocks.html" },
    { name: "Tetris", url: "/tetris.html" },
    { name: "Tetris 99", url: "/tetris-99.html" },
    { name: "Tetris Flash", url: "/tetris-flash.html" },
    { name: "The Impossible Quiz", url: "/the-impossible-quiz.html" },
    { name: "The Little Giant", url: "/the-little-giant.html" },
    { name: "There Is No Game", url: "/there-is-no-game.html" },
    { name: "Thunderdogs Io", url: "/thunderdogs-io.html" },
    { name: "Time Clones", url: "/time-clones.html" },
    { name: "Tingly Pyramid Solitaire", url: "/tingly-pyramid-solitaire.html" },
    { name: "Tiny Fishing", url: "/tiny-fishing.html" },
    { name: "Tinytownracing", url: "/tinytownracing.html" },
    { name: "Toaster Dash", url: "/toaster-dash.html" },
    { name: "Tomb Of The Mask", url: "/tomb-of-the-mask.html" },
    { name: "Tomb Of The Mask Color", url: "/tomb-of-the-mask-color.html" },
    { name: "Toon Off", url: "/toon-off.html" },
    { name: "Top Speed 3D", url: "/top-speed-3d.html" },
    { name: "Top Speed Racing 3D", url: "/top-speed-racing-3d.html" },
    { name: "Total Recoil", url: "/total-recoil.html" },
    { name: "Touchdowners", url: "/touchdowners.html" },
    { name: "Tower Of Destiny", url: "/tower-of-destiny.html" },
    { name: "Towntopia", url: "/towntopia.html" },
    { name: "Traffic Escape", url: "/traffic-escape.html" },
    { name: "Traffic Rider", url: "/traffic-rider.html" },
    { name: "Traffic Rush", url: "/traffic-rush.html" },
    { name: "Tricks", url: "/tricks.html" },
    { name: "Trivia Crack", url: "/trivia-crack.html" },
    { name: "Truck Loader", url: "/truck-loader.html" },
    { name: "Truck Loader 2", url: "/truck-loader-2.html" },
    { name: "Truck Loader 3", url: "/truck-loader-3.html" },
    { name: "Truck Loader 4", url: "/truck-loader-4.html" },
    { name: "Truck Loader 5", url: "/truck-loader-5.html" },
    { name: "True Love Calculator", url: "/true-love-calculator.html" },
    { name: "Tumble Wrestling", url: "/tumble-wrestling.html" },
    { name: "Tunnel Rush", url: "/tunnel-rush.html" },
    { name: "Turbo Moto Racer", url: "/turbo-moto-racer.html" },
    { name: "Twice", url: "/twice.html" },
    { name: "Twirl", url: "/twirl.html" },
    { name: "Two Button Bounce", url: "/two-button-bounce.html" },
    { name: "Two Neon Boxes", url: "/two-neon-boxes.html" },
    { name: "Ultimate Car Driving", url: "/ultimate-car-driving.html" },
    { name: "Ultimate Tic Tac Toe", url: "/ultimate-tic-tac-toe.html" },
    { name: "Unicycle Hero", url: "/unicycle-hero.html" },
    { name: "Unicycle Legend", url: "/unicycle-legend.html" },
    { name: "Unpuzzler", url: "/unpuzzler.html" },
    { name: "Vex 3", url: "/vex-3.html" },
    { name: "Vex 4", url: "/vex-4.html" },
    { name: "Vex 5", url: "/vex-5.html" },
    { name: "Vex 6", url: "/vex-6.html" },
    { name: "Vex 7", url: "/vex-7.html" },
    { name: "Vex 8", url: "/vex-8.html" },
    { name: "Village Craft", url: "/village-craft.html" },
    { name: "Villain Quinn My Drawing Portfolio", url: "/villain-quinn-my-drawing-portfolio.html" },
    { name: "War Of Caribbean Pirates", url: "/war-of-caribbean-pirates.html" },
    { name: "Water Color Sort", url: "/water-color-sort.html" },
    { name: "Water Polo Ragdoll", url: "/water-polo-ragdoll.html" },
    { name: "We Become What We Behold", url: "/we-become-what-we-behold.html" },
    { name: "We Skate", url: "/we-skate.html" },
    { name: "Westoon", url: "/westoon.html" },
    { name: "Where Is My Cat", url: "/where-is-my-cat.html" },
    { name: "Who Is", url: "/who-is.html" },
    { name: "Wizard Mike", url: "/wizard-mike.html" },
    { name: "Wood Blocks 3D", url: "/wood-blocks-3d.html" },
    { name: "Word Boss", url: "/word-boss.html" },
    { name: "Word City Crossed", url: "/word-city-crossed.html" },
    { name: "Word Monsters", url: "/word-monsters.html" },
    { name: "Wordle Unlimited", url: "/wordle-unlimited.html" },
    { name: "Wordoku", url: "/wordoku.html" },
    { name: "Words Search Classic Edition", url: "/words-search-classic-edition.html" },
    { name: "Wordy Pop", url: "/wordy-pop.html" },
    { name: "Worlds Hardest Game 2", url: "/worlds-hardest-game-2.html" },
    { name: "Worlds Hardest Game 3", url: "/worlds-hardest-game-3.html" },
    { name: "Yarn Untangle", url: "/yarn-untangle.html" },
    { name: "Yummy Toast", url: "/yummy-toast.html" },
    { name: "Zeepkist Crash 2D", url: "/zeepkist-crash-2d.html" },
    { name: "Zombie Derby Pixel Survival", url: "/zombie-derby-pixel-survival.html" },
    { name: "Zombie Outbreak Arena", url: "/zombie-outbreak-arena.html" },
    { name: "Zombie Siege Outbreak", url: "/zombie-siege-outbreak.html" },
    { name: "Zombotag", url: "/zombotag.html" },
    { name: "Zoom Be", url: "/zoom-be.html" },
    { name: "Zoom Be 2", url: "/zoom-be-2.html" },
    { name: "Zoom Be 3", url: "/zoom-be-3.html" },
    { name: "Zooplop", url: "/zooplop.html" },
    { name: "Zuma Boom", url: "/zuma-boom.html" },
];
